services:
 #api:
 #   container_name: api
 #   build:
 #     context: .
 #     dockerfile: Dockerfile
 #   ports:
 #     - "8080:8080"
 #   volumes:
 #     - ./:/app
 #   depends_on:
 #     - postgresdb
    #environment:
    #  - POSTGRES_USER=postgres
    #  - POSTGRES_PASSWORD=password
    #  - POSTGRES_DB=jccm
    #  - DATABASE_HOST=postgresdb
    #  - DATABASE_PORT=5432

 postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jccm
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
 db:
    driver: local
